### ISSUE TITLE
動画ページから別の動画に遷移する際、拡張機能が再読み込みされない

### ISSUE THREAD

**Issue by nk7540** [ryo-naka/note_on_youtube#3]

**Comment by nk7540** [comment]
動画ページから別の動画に遷移する際、YouTubeではURLでページ遷移せずに動画要素等必要な箇所だけDOMを置き換えているので、拡張が再読み込みされない。
これの解決策として

1. chrome.tabs.onUpdatedでurlの変更を掴めないか。
→contents_scriptの方でExtension context invalidatedというエラーが出て詰む。そもそもbackgroundのデバッグでもchangeInfo.urlに変化は検出されなかった。

2. 別の動画clickでeventを発生させ、sendMessageでbackgroundからchrome.runtime.reload()を行う。
→未検証。chrome.runtime.reload()がどういう動作をするのか怪しい。

3. 同じくclick eventで、chrome.tabs.reload()で無理やりページを再読み込み
→最終手段。非常に効率が悪いが、現状この動画リロードを手動で行なっているという状況なのでそこを自動化するという観点。

**Comment by nakashima-ryo-cyberwave** [comment]
下記commitで、1秒単位のpollingで動画遷移を検知するように実装(Rocket Noteを参照)
https://github.com/ryo-naka/note_on_youtube/commit/4b33c1e733b2f45d923a0bbde65825be1b4d24c6

**Comment by nk7540** [comment]
下記commitで、1秒単位のpollingで動画遷移を監視するよう実装
https://github.com/ryo-naka/note_on_youtube/commit/4b33c1e733b2f45d923a0bbde65825be1b4d24c6
